"""initial_schema

Revision ID: 6b0206e40620
Revises: 
Create Date: 2026-09-30 15:43:56.109009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0206e40620'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounts',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('branch_name', sa.String(length=128), nullable=False),
        sa.Column('branch_code', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_branch_code'), 'accounts', ['branch_code'], unique=True)

    op.create_table(
        'users',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('account_id', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=128), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table(
        'password_reset_tokens',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('token_hash', sa.String(length=255), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)

    op.create_table(
        'documents',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('account_id', sa.String(length=64), nullable=False),
        sa.Column('uploaded_by', sa.String(length=64), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=512), nullable=False),
        sa.Column('version', sa.String(length=32), nullable=False),
        sa.Column('doc_type', sa.String(length=64), nullable=False),
        sa.Column('effective_date', sa.Date(), nullable=False),
        sa.Column('superseded_by', sa.String(length=64), nullable=True),
        sa.Column('is_discontinued', sa.Boolean(), nullable=False),
        sa.Column('total_pages', sa.Integer(), nullable=False),
        sa.Column('total_chunks', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['superseded_by'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_account_id'), 'documents', ['account_id'], unique=False)
    op.create_index(op.f('ix_documents_is_discontinued'), 'documents', ['is_discontinued'], unique=False)

    op.create_table(
        'compliance_audit_logs',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('account_id', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('query', sa.Text(), nullable=False),
        sa.Column('rewritten_query', sa.Text(), nullable=True),
        sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=False),
        sa.Column('similarity_score', sa.Float(), nullable=False),
        sa.Column('response', sa.Text(), nullable=False),
        sa.Column('is_refusal', sa.Boolean(), nullable=False),
        sa.Column('latency_ms', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audit_logs_account_id'), 'compliance_audit_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_created_at'), 'compliance_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_user_id'), 'compliance_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_audit_logs_user_id'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_created_at'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_account_id'), table_name='compliance_audit_logs')
    op.drop_table('compliance_audit_logs')

    op.drop_index(op.f('ix_documents_is_discontinued'), table_name='documents')
    op.drop_index(op.f('ix_documents_account_id'), table_name='documents')
    op.drop_table('documents')

    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')

    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')

    op.drop_index(op.f('ix_accounts_branch_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
